repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch
      args: ['--pattern', '/^((?!(feature|bugfix|breaking)\/(DATA-)[0-9]{3,}_).)*$/gm']

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak=md]
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - --args=--disable-rule=terraform_required_version
        - --args=--disable-rule=terraform_required_providers
        - --args=--disable-rule=terraform_unused_declarations
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=./README.md
        - --hook-config=--add-to-exiting-file=true
        - --hook-config=--create-file-if-not-exist=true
        - --args=--sort-by required
    - id: terraform_checkov
      args:
        - --args=-d .
        - --args=--skip-check CKV2_GIT_1

- repo: https://github.com/Yelp/detect-secrets.git
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    name: Detect secrets
    always_run: true
    description: Detects high entropy strings that are likely to be passwords.
    entry: detect-secrets-hook
    files: .*\.(json|yml|yaml|tf)$
